ALTER TABLE people
ADD Phone CHARACTER VARYING(20);
ALTER TABLE people
DROP COLUMN Age;
ALTER TABLE people
ALTER COLUMN Surname TYPE TEXT;
ALTER TABLE people
ALTER COLUMN Phone
SET NOT NULL;
ALTER TABLE people
ALTER COLUMN Phone
DROP NOT NULL;
ALTER TABLE people
RENAME COLUMN Peoplename to FirstName;